### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by madtulip** [BSData/runewars#55]
Hello. Id like to join and fix i.e. some typos. Thanks! :)

**Comment by Cultiststeve** [comment]
Awesome. It will be good to have someone else working on this.
@amis92 or another admin should give you dev permissions when he sees this :)

**Comment by amis92** [comment]
Hello, @madtulip. Please accept the invitation on the [repo page](https://github.com/BSData/runewars/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
