### ISSUE TITLE
[Anon] Bug report: Daqan_Lords_(2017) 170731202346167.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/runewars#56]
**File:** Daqan_Lords_(2017) 170731202346167.catz

**BattleScribe version:** 2.01.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Runewars 1.3.1, Daqan Lords: Upgrade Problem

I have a 3x3 spearmen unit. In this size would have to upgrade heavy. I can not find an upgrade.

For Waiqar and the elves the upgrade is correct.

**Comment by Cultiststeve** [comment]
Thank you for the report. Fixed in  newest version.
