### ISSUE TITLE
Should remove dates from names of files and from names in battlescribe.

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/runewars#59]
Not required

**Comment by amis92** [comment]
Hi, just to help you with that, I've summarized it in Wiki: https://github.com/BSData/bsdata/wiki/Developer-Guide#most-common-mistakes

Hope that helps!

PS. There's also note about `backups` folder. It's unnecessary and may actually cause issues in future!

**Comment by Cultiststeve** [comment]
Looks like I am stuck with the _2017 on the end of each file?

Would be much nicer looking to remove it but I will take your advice that it will break things and leave it.

**Comment by Cultiststeve** [comment]
*even worse because 1 file is missing the _ between name and year. So inconsistant*

**Comment by Cultiststeve** [comment]
Also, some internal names have a year in. Ideally, they would also be removed. But see above link for reasons not to.

**Comment by amis92** [comment]
Well, internal names can be modified with no real impact on user experience, so that you can do :)

**Comment by Cultiststeve** [comment]
Ah I see, misread the line about changing internal name. Thanks again for help :)
