### ISSUE TITLE
Latest file is not showing up in release on website

### ISSUE THREAD

**Issue by Cultiststeve** [BSData/runewars#60]
Latest file of latari elves (v9) is not showing up on battlescribe data website. When syncing data old version (v6) is downloaded.
Correct version does appear to be in release on github.

Any suggestions from admins would be much appreciated.

**Comment by Cultiststeve** [comment]
Other files appear to be correct version. Only one file?

**Comment by Cultiststeve** [comment]
Will make a new release to see if that fixes.

**Comment by Cultiststeve** [comment]
@amis92 I still seem to be having this problem after creating a new release. Any ideas what could cause this?

**Comment by amis92** [comment]
Certainly the /backups folder doesn't help, but I don't have direct access to the webapp, so I can't tell you exactly what's wrong. How long since you've made the release?

**Comment by Cultiststeve** [comment]
The latest release was made 2 days ago. I have removed the backups folder and created a new release. That is likely the cause, as the backup folder version of the file was being hosted. 

Will update once the new release has made its way to hosted website. Thanks for help.

**Comment by amis92** [comment]
Seems like it worked!

**Comment by Cultiststeve** [comment]
It did, excellent. Thanks for catching my mistake 😀.
