### ISSUE TITLE
[Anon] Bug report: Latari_Elves_(2017) 170731201736475.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/runewars#62]
**File:** Latari_Elves_(2017) 170731201736475.catz

**BattleScribe version:** 2.01.09

**Platform:** Linux

**Dropbox:** No

**Description:** It is not possible to make any selections (number of trays etc.) for the Deepwood Archers Infantry unit.  Hovering over them also reveals no data.

**Comment by janstals** [comment]
Screenshot
![bsbug](https://user-images.githubusercontent.com/16412151/34778145-4a076820-f614-11e7-98f5-af6d65c53bf9.png)

**Comment by Cultiststeve** [comment]
Thanks for the report. This is related to issue #60 where the battle scribe data website is hosting an old version of the lateri file.

I am asking the hosts how to fix. In the mean time you can get the latest version of the file directly from the git hub. Please do let me know if you have any issues with it (Currently revision 10 for the lateri elves, where the hosted file is revision 6).

**Comment by janstals** [comment]
Downloading the data file directly from git hub fixed the issue.  This can be closed. Thank you.
