### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by 7falcon7wings7** [BSData/runewars#69]
I would like to help in updating the repositories for the Runewars Miniatures Game by Fantasy Flight. I have noticed that new units that have been released for the game are missing. I understand that FFG has pulled its OP support but my wife and I would like to contribute in supporting the game system. One of those ways is making sure that lists using the BattleScribe app are updated. While new to the GitHub site, I am currently working through the tutorials so I can be effective in writing the necessary code. Thanks!

**Comment by Cultiststeve** [comment]
Awesome. I'm happy to give you a hand if you run into any specific issues or have questions about the existing files.

**Comment by 7falcon7wings7** [comment]
Thanks! Now, according to the "Get Started" page, I'm supposed to get an email with an invitation to collaborate on the repository. Could you send me that email, or is there newer way of me accessing that? Also, when I open the GitHub app on my Mac, I do not see the BSData repo option on the list. Currently, I only see this on the window:
<img width="1680" alt="screenshot" src="https://user-images.githubusercontent.com/46388198/52919696-29115200-32d3-11e9-93a3-4d68963e6b7d.png">

Should I just go directly to https://github.com/BSData/runewars and clone it from there using the desktop app?

**Comment by Cultiststeve** [comment]
Amis should be able to send you a link to collaborate when he sees this. (Which gives you permission to push code into this repo directly).

For now, I would recommend forking this repo. This will create a version that your GitHub account owns. (I don't use the GitHub desktop app but it looks like the forked repo should show up there once you have forked)

**Comment by amis92** [comment]
Hello, @7falcon7wings7. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/runewars/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
