### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by DarthTelson** [BSData/runewars#70]
I have updated the files for Runewars on BattleScribe to include all units and upgrades released. I'd like permission granted so I can upload those files.

**Comment by amis92** [comment]
@Cultiststeve I'll interpret your thumbs-up as an approval :)

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/331672485)
:robot: Invited @DarthTelson with **push** access. Invite can be accepted on https://github.com/BSData/runewars/invitations
